### ISSUE TITLE
License

### ISSUE THREAD

**Issue by juholeinonen** [Ighina/DeepTiling#3]
Hi!

Really appreciate this repository, been helpful to my research. I'd like to build something on top of this, but cannot see what license you have. Is it MIT?

Thanks for you work!
Juho

**Comment by Ighina** [comment]
Hello Juho,

Thank you very much for the appreciation. Yes the license is MIT (Just added the license file). Also, if you use this software in publications can you please quote the original paper as 

Iacopo Ghinassi. (2021, May 9). Unsupervised Text Segmentation via Deep Sentence Encoders: a first step towards a common framework for text-based segmentation, summarization and indexing of media content. 2nd International Workshop on Data-driven Personalisation of Television (DataTV-2021) at the ACM International Conference on Interactive Media Experiences (IMX 2021) (DataTV-2021). https://doi.org/10.5281/zenodo.4744399

All the best,
Iacopo
