### ISSUE TITLE
What should be in all the "data/training_Data" in all of those commands

### ISSUE THREAD

**Issue by laiviet** [Ighina/DeepTiling#4]
The description looks long but could have been more helpful tbh. It needs more detail so one can run the code successfully. 
For example, folder structure and file format. I would really appreciate your time because it just takes you a few mins to show examples of file format, but it will take 10s of other x hours to figure out how to run your code.

Thanks

**Comment by Ighina** [comment]
It is unclear what you deem unclear tbh. I assume what you're missing is what to feed the -data parameter of the segment.py script (and consequently of the summarization and semantic search scripts). If that is the case, you need to provide the name of the directory in which you have the documents you want to segment, being those any text file.
For example:
python segment.py -data your_folder -wd 10 -th 1.5

with your_folder:
- your_folder
   - textfile1.txt
   - textfile2.txt
   - textfile3.txt
   - etc.
 
The three lines that read the file are:

file = open(str(path), "r")
raw_content = file.read()
file.close()

In wikiloader_sentences.py. An error that might arise is that of feeding documents with an unrecognised encoding, which at the moment will be platform specific (see https://docs.python.org/3/library/functions.html#open) as no encoding is provided to the open function. Let me know if you have problem with that or if this was indeed your question.

P.S. I am also adding a section in the readme to specify directory and file formats.
