### ISSUE TITLE
segeval error when running the fit.py command on the wiki_test_50 and the config_file parameters.json.

### ISSUE THREAD

**Issue by yasminee99** [Ighina/DeepTiling#8]

**Comment by yasminee99** [comment]
'Reference and hypothesis segmentations differ in position length ({0} is not {1}).'.format(len(reference), len(hypothesis)))
segeval.util.SegmentationMetricError: Reference and hypothesis segmentations differ in position length (31 is not 28).

error in the two files deeptilingModels.py  line 328 :                      
 segeval.convert_nltk_to_masses(reference, boundary_symbol=boundary_symb)[:-1])
and another error in the file fit.py line 147:
 Pk.append(deeptiling.compute_Pk(boundaries = results[-1]['boundaries'], ground_truth = long_true_lab[:-1], window_size=None))

**Comment by Ighina** [comment]
Hi,

The bug has now been fixed. I somehow introduced a mistake in the compute_pk method of DeepTiling, but I amended it and run the programme on my side: everything looks good now.
